### ISSUE TITLE
Manually define a rule to classify FR-I/FR-II galaxies

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/thursday#1]

**Comment by josh-marsh** [comment]
Here are the metrics for this dangerously simple rule. It's better than random, so that's something. See the latest commit for code and explanations.

Balanced Accuracy: 0.5329390418367703
Recall: 0.35772357723577236
Accuracy: 0.5870786516853933
F1 Score: 0.37446808510638296
Confusion Matrix
[[  44.   68.]
 [ 165.   79.]]
Precision: 0.39285714285714285

**Comment by MatthewJA** [comment]
Interesting that the accuracy is lower than my extremely great classifier, but the balanced accuracy is (of course) higher. Could you add some description of how the rule works into your notebook? You can add text cells in Jupyter notebooks &mdash; just a paragraph or so on what you're doing can really help readability. Then we can close this.

**Comment by josh-marsh** [comment]
Sorry didn't calculate the balanced accuracy on your classifier. Committed with an [explanation](https://github.com/MatthewJA/thursday/commit/ef47310737e4640b9a2685ed1d64d88bb70af389).

**Comment by MatthewJA** [comment]
Great, we can close this issue now.

For the record the balanced accuracy of my classifier is exactly 50%.
